name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
        # Configurar o agente SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Construir as imagens Docker
        run: docker-compose -f docker-compose.yml build

      - name: Subir containers Docker (Testar localmente)
        run: docker-compose -f docker-compose.yml up -d

      - name: Rodar testes (se houver)
        run: docker exec api-erp ./run-tests.sh 

      - name: Deploy na EC2
        run: |
          ssh -i /path/to/your-key.pem ec2-user@{{ secrets.IP_EC2 }} 'docker-compose -f /path/to/your/docker-compose.yml up -d'
